# https://docs.astral.sh/uv/guides/integration/github/

jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
#           - "3.10"
#           - "3.11"
#           - "3.12"
#           - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-groups

      - name: Run pytest using coverage
        run: uv run coverage run -m pytest
        run: uv run coverage combine
        run: uv run coverage report
        run: uv run coverage html
        run: uv run pytest
